### ISSUE TITLE
Changing the Microcontroller

### ISSUE THREAD

**Issue by derUser19** [4pplet/waffling60#1]
Are there any plans on using a different microcontroller since the ATMEGA32U2 has a shortage?

I'm new to this and tried to create a PCB but the ATMEGA32U2 is out of stock (apparently for the next months)

thanks for the info

**Comment by 4pplet** [comment]
Sorry for the delayed answer. I have been considering to maybe switch MCU to the RP2040 when QMK and ZMK ports are complete. The STM32 situation is not much better, so I'd not want to redesign the project to potentially have another MCU that's not in stock. Hopefully we will see the ATMEGA32U2 back in stock soon.
