### ISSUE TITLE
ISO return switch should be rotated 90º

### ISSUE THREAD

**Issue by danbee** [4pplet/waffling60#2]
Hi! This looks like a super interesting project. I'm really interested in building an ISO hotswap PCB but I just wanted to let you know that the switch for the return key needs to be rotated by 90 degrees.

**Comment by 4pplet** [comment]
Hi @danbee ! Thanks for showing interest in the project 👍 

Afaik the current rotation is the more common one, it's what's generally used by Cherrys own keyboards.

**Comment by danbee** [comment]
Hi @4pplet, I have several pre-built ISO boards, including a Cherry G80-3000 and the enter keyswitch is rotated 90 degrees in every case. Here's a few pictures I dug up off the Internet showing this. The first is a Cherry G80-3000 and the second is a WASD V3.

![image](https://github.com/4pplet/waffling60/assets/165531/f78f6836-0f9e-496d-bc4b-2fa783297a8f)

![image](https://github.com/4pplet/waffling60/assets/165531/34569548-ead7-464e-a1d1-8486a2cd5713)

I've definitely seen both orientations, but I believe the 90 degree rotation is correct, as I have experienced very tight fitting keycaps on boards with the switch not rotated (specifically a DZ60) compared with boards with the switch rotated (E.g. a GH60).

Anyway, I hope you'll reconsider!

**Comment by 4pplet** [comment]
Hey @danbee ! 

I appreciate the detailed response, I'll for sure take it into consideration for future revisions 👍

**Comment by 4pplet** [comment]
Hey @danbee ! Just to let you know, the ISO enter rotation will be updated on the upcoming release (E). The design files are up, but all is not yet verified or supported in software (QMK + VIA).

Have a nice day!

**Comment by danbee** [comment]
@4pplet That's awesome, thanks for letting me know!
